### ISSUE TITLE
Neovim plugin seems to be calling 'Himalaya --mailbox' which is causing an error when I try to start it

### ISSUE THREAD

**Issue by devanlooches** [soywod/himalaya#90]
Hello,
Whenever I try to start Himalaya I get the following error:

```
	error: Found argument '--mailbox' which wasn't expected, or isn't valid in this context^@^@USAGE:^@    himalaya list [OPTIONS]^@^@For more information try --help^
```

Any help would be appreciated.
Thanks in advance!

**Comment by soywod** [comment]
Duplicate https://github.com/soywod/himalaya/issues/89. The JSON output seems to be broken since the last release, I will fix ASAP.

**Comment by soywod** [comment]
Fixed in [v0.2.5](https://github.com/soywod/himalaya/releases/tag/v0.2.5) :tada:

**Comment by devanlooches** [comment]
Hmm It doesn't seem to have fixed it. I reinstalled the cli and it still doesn't work :(

**Comment by soywod** [comment]
Did you update the vim plugin also?

**Comment by devanlooches** [comment]
Yes I did. I'll try again though.

**Comment by devanlooches** [comment]
Yup still gives the same error.

**Comment by soywod** [comment]
I can't reproduce. Can you give me your `himalaya --version`, the git commit hash of the vim plugin and your himalaya config?

**Comment by devanlooches** [comment]
sure:
* Himalaya --version returns: ``himalaya 0.2.5``
* It looks like the commit hash is ``9b91f256638e8bb31d4386bf0d7f897b674e9dda`` (I got that from doing git log inside the plugin folder. Was that the right thing to do?
* Here is my himalaya config:
```
name = "Devan Looches"
downloads-dir = "/Users/devan/Downloads"

[Devan]
email = "devan.looches@gmail.com"

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "devan.looches@gmail.com"
imap-passwd-cmd = "pass show devan.looches@gmail.com"

smtp-host = "smtp.gmail.com"
smtp-port = 487
smtp-login = "devan.looches@gmail.com"
smtp-passwd-cmd = "pass show devan.looches@gmail.com"


[SecondAccount]
name = "XXXX"
default = true
email = "my_other_email_here"

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "my_other_email_here"
imap-passwd-cmd = "pass show my_other_email_here"

smtp-host = "smtp.gmail.com"
smtp-port = 487
smtp-login = "my_other_email_here"
smtp-passwd-cmd = "pass show my_other_email_here"

```

**Comment by soywod** [comment]
It looks like the commit 9b91f256638e8bb31d4386bf0d7f897b674e9dda does not exists, so I guess it disappeared due to a force push. Maybe it's the reason why the plugin can't update. Can you try to reinstall it?

**Comment by devanlooches** [comment]
Yup I tried. (I deleted it from the config file, PlugCleaned it, and then put it back and PlugInstalled it) It still gives the same error.

**Comment by devanlooches** [comment]
Just fyi. I forgot to mention that the cli works fine. The only problem is the plugin.

**Comment by soywod** [comment]
Very strange. It really seems that the Vim plugin is not up-to-date. Could you try to clone manually this repo, then load the vim plugin manually by updating your `runtimepath` (add sth like `set rtp+=/path/to/himalaya/vim` to your config)? Sorry for all those manipulations, I really don't understand what is happening there.

**Comment by devanlooches** [comment]
No its ok. Thank you very much for taking the time to help me. I really appreciate it.

**Comment by devanlooches** [comment]
I tried manual installation and it still gives me the error.

**Comment by devanlooches** [comment]
Wait no sorry Its not installed properly yet.

**Comment by devanlooches** [comment]
What should the path be because just leading to the vim/ folder isn't working.

**Comment by soywod** [comment]
The pass should be the absolute path to `himalaya` folder followed by `/vim`, sth like `/my/abs/path/to/himalaya/vim`. It's what I do for me since I have the repo locally installed and it works well.

**Comment by devanlooches** [comment]
Hmm it still says that the Himalaya command isn't found. My path is ``/Users/devan/git_cloned_stuff/himalaya/vim/``

**Comment by soywod** [comment]
Try without the last slash?

**Comment by devanlooches** [comment]
Nope still does not work.

**Comment by soywod** [comment]
I will share my conf with you tomorrow. The rtp works well for me, so it should work for you also. Sth must be wrong somewhere :)

**Comment by devanlooches** [comment]
Thank you!

**Comment by soywod** [comment]
So here is my configuration:

- The himalaya sources are located at `~/Code/himalaya` (master branch @ 926f476194a66d6854d302f9f846e71b7880b72c)
- The vim plugin is located at `~/Code/himalaya/vim`
- I have in my `init.lua` this line: `vim.o.runtimepath = vim.o.runtimepath..',~/Code/himalaya/vim'` (which is the same as `set rtp+=,~/Code/himalaya/vim` for vim files)
- I'm now able to launch the vim command `:Himalaya` and it shows me my mails

**Comment by devanlooches** [comment]
Sorry I'm in the middle of rewriting my configuration in lua. I'll let you know when I test it. Thank you again for your help.

**Comment by devanlooches** [comment]
I just tested it with my new plugin manager (Paq) and it still doesn't work :(

**Comment by devanlooches** [comment]
It works!!! When I installed it manually it works!! Thank you!! I have no idea what changed. Maybe the Lua config made it work.

**Comment by devanlooches** [comment]
Wait it only works when I am inside the Himalaya directory actually.

**Comment by soywod** [comment]
> Wait it only works when I am inside the Himalaya directory actually.

This sounds like a configuration issue. Could you share it?

**Comment by devanlooches** [comment]
You mean my configuration? sure
here is my init.lua:
```
package.path = package.path..';'..'/Users/devan/.config/nvim/plugin/plugin.lua'
require('plugin/plugin')
package.path = package.path..';'..'/Users/devan/.config/nvim/settings.lua'
require('settings')
package.path = package.path..';'..'/Users/devan/.config/nvim/keybindings.lua'
require('keybindings')
-- Init Colorizer Plugin
require('colorizer').setup()
vim.o.runtimepath = vim.o.runtimepath..',~/Code/himalaya/vim'
```
keybindings.lua:
```
-- Git fugitive
buf_set_keymap('n', '<leader>gs', ':Git<CR>', opts)
buf_set_keymap('n', '<leader>gl', 'diffget //3<CR>', opts)
buf_set_keymap('n', '<leader>gh', 'diffget //2<CR>', opts)

-- Rust LSP Key Bindings
if pumvisible() then
-- Use <Tab> and <S-Tab> to navigate through popup menu
buf_set_keymap('i', '<expr> <Tab>', '\<C-n>', opts)
buf_set_keymap('i', '<expr> <S-Tab>', '\<C-p>', opts)
end

-- use <Tab> as trigger keys
buf_set_keymap('i', '<Tab>', '<Plug>(completion_smart_tab)', opts)
buf_set_keymap('i', '<Tab>', '<Plug>(completion_smart_s_tab)', opts)

-- Snippet Keymappings
buf_set_keymap('i', '<C-k>', '<Plug>(neosnippet_expand_or_jump)', opts)
buf_set_keymap('s', '<C-k>', '<Plug>(neosnippet_expand_or_jump)', opts)
buf_set_keymap('x', '<C-k>', '<Plug>(neosnippet_expand_or_jump)', opts)

-- Telescope Keybindings
buf_set_keymap('n', '<leader>ff', '<cmd>Telescope find_files<cr>', opts)
buf_set_keymap('n', '<leader>fg', '<cmd>Telescope live_grep<cr>', opts)
buf_set_keymap('n', '<leader>fb', '<cmd>Telescope buffers<cr>', opts)
buf_set_keymap('n', '<leader>fh', '<cmd>Telescope help_tags<cr>', opts)
buf_set_keymap('n', '<leader>fc', '<cmd>Telescope commands<cr>', opts)

-- Fast reload configuration
buf_set_keymap('n', '<leader>r', '<cmd>source ~/.config/nvim/init.lua<cr>', opts)
```
settings.lua:
```
vim.o.swapfile = false
vim.o.ch = 2
vim.o.showmode = false
vim.o.termguicolors = true
vim.o.syntax = 'enable'
vim.o.shortmess = vim.o.shortmess .. 'c'
vim.cmd 'filetype plugin indent on'
vim.g.mapleader = ' '
vim.b.mapleader = ' '
vim.wo.number = true
vim.wo.relativenumber = true
vim.g.spell = true
vim.g.spelllang = 'en_us'
vim.o.clipboard = 'unnamed,unnamedplus'
vim.cmd 'au BufWinEnter * silent! loadview'
vim.cmd 'au BufWinLeave * mkview!'
vim.cmd 'colorscheme night-owl'
vim.o.completeopt = 'menuone,noinsert,noselect'
vim.o.updatetime = 300
vim.o.foldmethod = 'expr'
vim.o.foldexpr = 'nvim_treesitter#foldexpr()'
```
plugin/plugin.lua:
```
vim.cmd 'packadd paq-nvim'         -- Load package
local paq = require'paq-nvim'.paq  -- Import module and bind `paq` function
paq{'savq/paq-nvim', opt=true}
	-- Packer can manage itself as an optional plugin
	paq {'wbthomason/packer.nvim', opt=true}

	-- Status Bar
	paq 'itchyny/lightline.vim'
	
	-- Email in Neovim!!!
	--paq 'soywod/himalaya.vim'

	-- Control AppleMusic/Spotify (only for macos)
	paq {'srishanbhattarai/neovim-spotify', installer='bash install.sh'}
	
	-- Autoclose
	paq 'jiangmiao/auto-pairs'

	-- Snippets
	paq 'Shougo/neosnippet.vim' 
	paq 'Shougo/neosnippet-snippets'

	-- Vim Cool
	paq 'romainl/vim-cool'

	-- Vim Telescope
	paq 'nvim-lua/popup.nvim'
	paq 'nvim-lua/plenary.nvim'
	paq 'nvim-telescope/telescope.nvim'
	paq 'nvim-telescope/telescope-fzy-native.nvim'

	-- Commenting
	paq 'tpope/vim-commentary'

	-- Table Mode
	paq 'dhruvasagar/vim-table-mode'

	-- Colorscheme
	paq 'haishanh/night-owl.vim'

	-- Vim Tips
	paq 'michaelb/vim-tips'

	-- Colorezire For Neovim
	paq 'norcalli/nvim-colorizer.lua'

	-- Collection of common configurations for the Nvim LSP client
	paq 'neovim/nvim-lspconfig'

	-- Extensions to built-in LSP, for example, providing type inlay hints
	paq 'nvim-lua/lsp_extensions.nvim'

	-- Auto completion framework for built-in LSP
	paq 'nvim-lua/completion-nvim'

	-- Emmet for Neovim
	paq 'mattn/emmet-vim'

	-- Syntax highlighting
	paq {'nvim-treesitter/nvim-treesitter', updater='TSUpdate'}

	-- Git wrapper
	paq 'tpope/vim-fugitive'

	-- Rich Presence for Discord
	paq 'andweeb/presence.nvim'

	-- Live markdown
	paq {'euclio/vim-markdown-composer', installer='cargo build --release'}
```
(I also have like 10 other files to configure each plugin so I can share those if you want)

**Comment by soywod** [comment]
> `vim.o.runtimepath = vim.o.runtimepath..',~/Code/himalaya/vim'`

This you need to adapt with your own path. I don't know where is located the folder himalaya but it should be sth like `/User/devan/himalaya/vim`.

**Comment by devanlooches** [comment]
I git cloned to ``~/Code/himalaya``. So that I did the same exact thing as you.

**Comment by soywod** [comment]
And if you replace the `~` by the abs path (`/Users/devan` I guess)? You still can't run the command `:Himalaya` inside vim?

**Comment by devanlooches** [comment]
I changed it to ``/Users/devan`` and it works!!!

**Comment by devanlooches** [comment]
Thank you again for your time!
bonne journée ;)

**Comment by devanlooches** [comment]
However, I still am unable to switch accounts in the plugin the error is
```Vim(call):E488: Trailing characters```

**Comment by soywod** [comment]
What do you mean by accounts? Mailboxes?

**Comment by devanlooches** [comment]
Yes sorry I mean mailboxes

**Comment by soywod** [comment]
Which version on vim/neovim do you use?

**Comment by devanlooches** [comment]
```v0.5.0-dev+b518b9076```

**Comment by soywod** [comment]
And if you add to your configuration `vim.g['himalaya_mailbox_picker'] = 'telescope'`? If not then try `vim.g['himalaya_mailbox_picker'] = 'native'`.

**Comment by devanlooches** [comment]
The second worked! Thank you

**Comment by devanlooches** [comment]
How do I change accounts?

**Comment by soywod** [comment]
This is not implemented yet, see #91.

**Comment by devanlooches** [comment]
Got it. Thank you. Thank you for your time again.
Bonne Journée ;)

**Comment by soywod** [comment]
You are welcomed ;)
